version: '3'

services:

  server:
    build:
      dockerfile: deployments/server.Dockerfile
      context: .
    restart: always

  client:
    build:
      dockerfile: deployments/client.Dockerfile
      context: .
    restart: always
    depends_on:
      - server
    links:
      - server
    environment:
      - SERVER_ADDRESS=server:8080
