port: "8080"
requests-creation-timeout: 50       # in ms
requests-per-client: 50                  # number of requests to send
  RequestsPerClient
server-address: "localhost:8080"    # remote server address
hashcash-zeros-count: 3             # number of zeros for hashcash
hashcash-timeout: 300               # in sec
hashcash-max-iterations: 1000000    # to solve PoW Hashcash challenge